import os

WEBHOOK_BASE_URL = os.getenv("WEBHOOK_BASE_URL", "http://127.0.0.1:8000").rstrip("/")
ELEVENLABS_WEBHOOK_SECRET = os.getenv("ELEVENLABS_WEBHOOK_SECRET", "")

CAMPAIGN_BATCH_SIZE = int(os.getenv("CAMPAIGN_BATCH_SIZE", "10"))
CAMPAIGN_BATCH_DELAY_SECONDS = float(os.getenv("CAMPAIGN_BATCH_DELAY_SECONDS", "2"))
